# Use postgres/ user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 5432:5432
